# Generated by Django 5.2.15 on 2026-06-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
                ('Degree_selected', models.CharField(choices=[('Software Engineering', 'Software'), ('Computer Science', 'Computer'), ('Business Administration', 'Bba')], default='Software Engineering', max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
