# Generated by Django 5.2.15 on 2026-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employes_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='designation',
            field=models.CharField(default='Employes', max_length=50),
        ),
    ]
