# Generated by Django 5.2.15 on 2026-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.CharField(default='IT', max_length=100),
        ),
    ]
