# Generated by Django 5.2.15 on 2026-06-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes_api', '0002_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.CharField(choices=[('Software Engineering', 'SE'), ('Information Technology', 'IT'), ('Computer Science', 'CS')], default='Software Engineering', max_length=100),
        ),
    ]
